# Numpy

## Clase 4 Dimensiones

- 0 Escalar
- 1 Vector
- 2 matriz
- [3,N] tensor

In [297]:
import numpy as np

In [298]:
scalar = np.array(42)
print(scalar)
print("Dimensión: ",scalar.ndim)

42
Dimensión:  0


In [299]:
vector = np.array([1,2,3])
print(vector)
print("Dimensión: ",vector.ndim)

[1 2 3]
Dimensión:  1


In [300]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
print("Dimensión: ",matriz.ndim)

[[1 2 3]
 [4 5 6]]
Dimensión:  2


In [301]:
tensor = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(tensor)
print("Dimensión: ",tensor.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Dimensión:  3


### Agregar o eliminar dimensiones

In [302]:
vector = np.array([1,2,3], ndmin=10)
print(vector)
print("Dimensión: ",vector.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]]
Dimensión:  10


In [303]:
expand = np.expand_dims(np.array([1,2,3]),axis=0)
print(expand)
print("Dimensión: ",expand.ndim)

[[1 2 3]]
Dimensión:  2


In [345]:
expand = np.expand_dims(np.array([1,2,3]),axis=1)
print(expand)
print("Dimensión: ",expand.ndim)

[[1]
 [2]
 [3]]
Dimensión:  2


In [344]:
print(vector,"Dimensión: ",vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2,"Dimensión: ",vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] Dimensión:  10
[1 2 3] Dimensión:  1


## Clase 5 Creación de arrays en numpy

In [305]:
import numpy as np

In [306]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [307]:
np.arange(-10,11,2)

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8,  10])

In [308]:
np.zeros(3)

array([0., 0., 0.])

In [309]:
np.ones((10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [310]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [311]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [312]:
np.random.rand()

0.5790626396738328

In [313]:
np.random.rand(4,4)

array([[0.28826335, 0.38325896, 0.65344757, 0.16005495],
       [0.62823407, 0.51415049, 0.51944943, 0.58874548],
       [0.56408662, 0.55452156, 0.24764998, 0.56101454],
       [0.79785667, 0.11079478, 0.17530035, 0.99469361]])

In [314]:
np.random.randint(1,100)

47

In [315]:
np.random.randint(0,100,(5,5))

array([[45, 77, 28, 38, 87],
       [ 5, 77, 23,  0, 94],
       [23, 52, 33, 35, 56],
       [49,  8, 52, 87, 44],
       [19, 69, 24, 47, 28]])

## Clase 6 Shape and Reshape

- Sirve para ...

In [316]:
import numpy as np

In [317]:
arr = np.random.randint(1,100,(3,2))
arr

array([[55, 10],
       [64, 60],
       [96, 46]])

In [318]:
# Muestra las cantidades por als dimensiones 3x2
arr.shape

(3, 2)

In [319]:
# Reshape cambia la forma en la que se establece el array de 3x2 a 1x6
arr.reshape(1,6)

array([[55, 10, 64, 60, 96, 46]])

In [320]:
arr.reshape(2,3)

array([[55, 10, 64],
       [60, 96, 46]])

In [321]:
arr.reshape(3,2)

array([[55, 10],
       [64, 60],
       [96, 46]])

In [322]:
# Como en el lenguaje C
np.reshape(arr,(2,3),'C')

array([[55, 10, 64],
       [60, 96, 46]])

In [323]:
# Como en el lenguaje Fortran
np.reshape(arr,(2,3),'F')

array([[55, 96, 60],
       [64, 10, 46]])

In [324]:
# selecciona el array en forma de leguaje C o Fortran
np.reshape(arr,(2,3),'A')

array([[55, 10, 64],
       [60, 96, 46]])

## Clase 7 Funciones principales de Numpy

In [325]:
import numpy as np

In [326]:
arr = np.random.randint(1,20,10)
arr

array([19, 19, 15,  6, 11,  6, 16, 13, 12, 14])

In [327]:
matriz = arr.reshape(2,5)
matriz

array([[19, 19, 15,  6, 11],
       [ 6, 16, 13, 12, 14]])

In [328]:
#Función MAX (trae el número mayor)
arr.max()

19

In [329]:
#por renglon
print(matriz.max(1))
# por columna
print(matriz.max(0))

[19 16]
[19 19 15 12 14]


In [330]:
# indice de valor máximo (muestra el de menor indice)
arr.argmax()

0

In [331]:
matriz.argmax(0)

array([0, 0, 0, 1, 1], dtype=int64)

In [332]:
# Similar a min para el minimo
matriz.min(0)

array([ 6, 16, 13,  6, 11])

In [333]:
matriz.argmin(0)

array([1, 1, 1, 0, 0], dtype=int64)

In [334]:
# función peak to peak (del menor al mayor)
print(arr)
arr.ptp()

[19 19 15  6 11  6 16 13 12 14]


13

In [335]:
arr.sort()
arr

array([ 6,  6, 11, 12, 13, 14, 15, 16, 19, 19])

In [336]:
np.percentile(arr,50)

13.5

### funciones estadisticas

In [337]:
np.median(arr)

13.5

In [338]:
np.std(arr)

4.346262762420146

In [339]:
np.var(arr)

18.89

In [340]:
np.std(arr) ** 2

18.889999999999997

In [341]:
np.mean(arr)

13.1

In [342]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [343]:
np.concatenate((a,b),axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
print(a.ndim)
print(b.ndim)

2
1


In [ ]:
b=np.expand_dims(b,axis=0)
b

array([[5, 6]])

In [ ]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.concatenate((a,b),axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [ ]:
#Transpuesta
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
print(b)
print(b.T)

[[5 6]]
[[5]
 [6]]


## Clase 8 Función Copy

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
trozo_arr = arr[0:6]
trozo_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
trozo_arr[:] = 0
trozo_arr

array([0, 0, 0, 0, 0, 0])

In [ ]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [ ]:
arr_copy = arr.copy()
arr_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [ ]:
arr_copy[:] = 1
print(arr_copy)
print(arr)

[1 1 1 1 1 1 1 1 1 1 1]
[ 0  0  0  0  0  0  6  7  8  9 10]


## Clase 9 Condiciones

In [ ]:
import numpy as np

In [ ]:
arr = np.linspace(1,10,10,dtype='int8')

In [ ]:
indices_condicion = arr > 5
indices_condicion

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [ ]:
arr[indices_condicion]
#or
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [ ]:
arr[(arr > 5) & (arr<9)]

array([6, 7, 8])

In [ ]:
arr[arr > 5 ] = 99
arr

array([ 1,  2,  4,  4,  5, 99, 99, 99, 99, 99])

## Clase 10 Operaciones

In [ ]:
import numpy as np

In [ ]:
lista = [1,2]
lista

[1, 2]

In [ ]:
lista * 2

[1, 2, 1, 2]

In [ ]:
arr = np.arange(0,10)
arr2 = arr.copy()

Operaciones

In [ ]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
1 / arr

C:\Users\Diego\AppData\Local\Temp\ipykernel_3584\1528351372.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [ ]:
np.matmul(matriz,matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [ ]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])

# Pandas

## Clase 1 Series y Dataframse en Pandas

Pandas maneja 2 objetos principales 

Pandas Series
y
Pandas Dataframe

In [1]:
import pandas as pd

In [2]:
psg_players=pd.Series(['Navas','Mbappe','Neymar','Messi'],
    index=[1,7,10,30]
    )

In [3]:
psg_players

1      Navas
7     Mbappe
10    Neymar
30     Messi
dtype: object

In [4]:
dict = {1:'Navas',2:'Mbappe',3:'Neymar',4:'Messi'}
pd.Series(dict)

1     Navas
2    Mbappe
3    Neymar
4     Messi
dtype: object

In [6]:
psg_players.loc[0:3]

1    Navas
dtype: object

In [8]:
dict_players = {'Jugador':['Navas','Mbappe','Neymar','Messi'],
'Altura':[183.0,170.0,170.0,165.0],
'Goles':[2,200,200,200]
}
dict_players

{'Jugador': ['Navas', 'Mbappe', 'Neymar', 'Messi'],
 'Altura': [183.0, 170.0, 170.0, 165.0],
 'Goles': [2, 200, 200, 200]}

In [10]:
df_players = pd.DataFrame(dict_players)
df_players

Jugador  Altura  Goles
0   Navas   183.0      2
1  Mbappe   170.0    200
2  Neymar   170.0    200
3   Messi   165.0    200

In [11]:
df_players.columns

Index(['Jugador', 'Altura', 'Goles'], dtype='object')

In [12]:
df_players.index

RangeIndex(start=0, stop=4, step=1)

## Clase 2 Leer archivos CSV y JSON con Pandas

In [13]:
import pandas as pd

In [23]:
df_books = pd.read_csv('./bestsellers-with-categories.csv',sep=',',header=0,names=['Namesss', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre'])

In [25]:
df_books.head(5)

Namesss  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  Price  Year        Genre  
0                  JJ Smith          4.7    17350      8  2016  Non Fiction  
1              Stephen King          4.6     2052     22  2011      Fiction  
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3             George Orwell          4.7    21424      6  2017      Fiction  
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction

In [27]:
pd.read_json('./hpcharactersdataraw.json').tail(5)

Name                                               Link  \
1935     Georgi Zdravko  https://www.hp-lexicon.org/character/georgi-zd...   
1936             Zograf       https://www.hp-lexicon.org/character/zograf/   
1937              Zonko        https://www.hp-lexicon.org/character/zonko/   
1938  Valentina Vázquez  https://www.hp-lexicon.org/character/valentina...   
1939      Zygmunt Budge  https://www.hp-lexicon.org/character/zygmunt-b...   

                                                  Descr  Gender Species/Race  \
1935  Georgi Zdravko played Keeper for the Bulgarian...    Male       Wizard   
1936  Zograf played Keeper for the Bulgarian Nationa...     NaN       Wizard   
1937  Founder(?) of Zonko’s Joke Shop. Possibly a re...     NaN      Unknown   
1938  Valentina Vázquez was President of the Argenti...  Female        Witch   
1939  Zygmunt Budge is considered to be one of the m...    Male       Wizard   

        Blood              School  \
1935  Unknown             Unknown   
1936  Unknown             Unknown   
1937  Unknown             Unknown   
1938  Unknown             Unknown   
1939  Unknown  Hogwarts - Student   

                                         Profession  
1935                      Quidditch player (Seeker)  
1936                      Quidditch player (Keeper)  
1937                                        Unknown  
1938  President of the Argentinian Council of Magic  
1939    Potions Master, Potioneer, Inventor, Author

## Clase 3 filtrado con loc y iloc

In [28]:
import pandas as pd

In [29]:
df_books = pd.read_csv('./bestsellers-with-categories.csv')

In [30]:
df_books[0:4]

Name              Author  User Rating  \
0            10-Day Green Smoothie Cleanse            JJ Smith          4.7   
1                        11/22/63: A Novel        Stephen King          4.6   
2  12 Rules for Life: An Antidote to Chaos  Jordan B. Peterson          4.7   
3                   1984 (Signet Classics)       George Orwell          4.7   

   Reviews  Price  Year        Genre  
0    17350      8  2016  Non Fiction  
1     2052     22  2011      Fiction  
2    18979     15  2018  Non Fiction  
3    21424      6  2017      Fiction

In [33]:
df_books[['Name','Author','Year']]

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  Year  
0                    JJ Smith  2016  
1                Stephen King  2011  
2          Jordan B. Peterson  2018  
3               George Orwell  2017  
4    National Geographic Kids  2019  
..                        ...   ...  
545               Jeff Kinney  2019  
546               Jen Sincero  2016  
547               Jen Sincero  2017  
548               Jen Sincero  2018  
549               Jen Sincero  2019  

[550 rows x 3 columns]

Loc

In [36]:
df_books.loc[0:4,['Name','Author']]

Name                    Author
0                      10-Day Green Smoothie Cleanse                  JJ Smith
1                                  11/22/63: A Novel              Stephen King
2            12 Rules for Life: An Antidote to Chaos        Jordan B. Peterson
3                             1984 (Signet Classics)             George Orwell
4  5,000 Awesome Facts (About Everything!) (Natio...  National Geographic Kids

In [37]:
df_books.loc[:,['Reviews']] * -1

Reviews
0     -17350
1      -2052
2     -18979
3     -21424
4      -7665
..       ...
545    -9413
546   -14331
547   -14331
548   -14331
549   -14331

[550 rows x 1 columns]

In [40]:
df_books.loc[:,['Author']] == 'JJ Smith'

Author
0      True
1     False
2     False
3     False
4     False
..      ...
545   False
546   False
547   False
548   False
549   False

[550 rows x 1 columns]

Iloc

In [44]:
# Iloc hace una busqueda por indice
df_books.iloc[:,0:4]

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  
0                    JJ Smith          4.7    17350  
1                Stephen King          4.6     2052  
2          Jordan B. Peterson          4.7    18979  
3               George Orwell          4.7    21424  
4    National Geographic Kids          4.8     7665  
..                        ...          ...      ...  
545               Jeff Kinney          4.9     9413  
546               Jen Sincero          4.7    14331  
547               Jen Sincero          4.7    14331  
548               Jen Sincero          4.7    14331  
549               Jen Sincero          4.7    14331  

[550 rows x 4 columns]

In [43]:
df_books.iloc[1,3] * -1

-2052

## Clase 4 agregar o eliminar datos con Pandas

In [45]:
import pandas as pd

In [68]:
df_books = pd.read_csv('./bestsellers-with-categories.csv',sep=',',header=0)
df_books.head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year        Genre  
0  2016  Non Fiction  
1  2011      Fiction

In [57]:
df_books.drop('Genre',axis=1,inplace=True)

In [58]:
df_books.head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year  
0  2016  
1  2011

In [59]:
# usando del de python
del df_books['Price']

In [62]:
df_books.head(2)

Name        Author  User Rating  Reviews  Year
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350  2016
1              11/22/63: A Novel  Stephen King          4.6     2052  2011

### Drop Rows

In [66]:
df_books.drop(range(0,10),axis=0).head(2)

Name            Author  \
10                          A Man Called Ove: A Novel   Fredrik Backman   
11  A Patriot's History of the United States: From...  Larry Schweikart   

    User Rating  Reviews  Year  
10          4.6    23848  2017  
11          4.6      460  2010

### Add Columns

In [69]:
df_books.head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year        Genre  
0  2016  Non Fiction  
1  2011      Fiction

In [71]:
import numpy as np

In [74]:
df_books['Nueva_Columna'] = np.nan
df_books.head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year        Genre  Nueva_Columna  
0  2016  Non Fiction            NaN  
1  2011      Fiction            NaN

In [75]:
df_books['Rango'] = np.arange(0,df_books.shape[0])

In [76]:
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  \
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   
1                Stephen King          4.6     2052     22  2011      Fiction   
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3               George Orwell          4.7    21424      6  2017      Fiction   
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction   
..                        ...          ...      ...    ...   ...          ...   
545               Jeff Kinney          4.9     9413      8  2019      Fiction   
546               Jen Sincero          4.7    14331      8  2016  Non Fiction   
547               Jen Sincero          4.7    14331      8  2017  Non Fiction   
548               Jen Sincero          4.7    14331      8  2018  Non Fiction   
549               Jen Sincero          4.7    14331      8  2019  Non Fiction   

     Nueva_Columna  Rango  
0              NaN      0  
1              NaN      1  
2              NaN      2  
3              NaN      3  
4              NaN      4  
..             ...    ...  
545            NaN    545  
546            NaN    546  
547            NaN    547  
548            NaN    548  
549            NaN    549  

[550 rows x 9 columns]

### Add rows

In [80]:
df_books.append(df_books[0:1])
#df_books[0:1]

C:\Users\DiegoJiménez\AppData\Local\Temp\ipykernel_23532\3089322899.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_books.append(df_books[0:1])


Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   
0                        10-Day Green Smoothie Cleanse   

                       Author  User Rating  Reviews  Price  Year        Genre  \
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   
1                Stephen King          4.6     2052     22  2011      Fiction   
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3               George Orwell          4.7    21424      6  2017      Fiction   
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction   
..                        ...          ...      ...    ...   ...          ...   
546               Jen Sincero          4.7    14331      8  2016  Non Fiction   
547               Jen Sincero          4.7    14331      8  2017  Non Fiction   
548               Jen Sincero          4.7    14331      8  2018  Non Fiction   
549               Jen Sincero          4.7    14331      8  2019  Non Fiction   
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   

     Nueva_Columna  Rango  
0              NaN      0  
1              NaN      1  
2              NaN      2  
3              NaN      3  
4              NaN      4  
..             ...    ...  
546            NaN    546  
547            NaN    547  
548            NaN    548  
549            NaN    549  
0              NaN      0  

[551 rows x 9 columns]

## Clase 5 Manejo de Nulos en Pandas

In [81]:
import pandas as pd
import numpy as np

In [83]:
dict = {
    'Col1':[1,2,3,np.nan],
    'Col2':[4,np.nan,6,7],
    'Col3':['a','b','c',None]
}

In [84]:
df = pd.DataFrame(dict)

In [85]:
df

Col1  Col2  Col3
0   1.0   4.0     a
1   2.0   NaN     b
2   3.0   6.0     c
3   NaN   7.0  None

In [87]:
df.isnull()*1

Col1  Col2  Col3
0     0     0     0
1     0     1     0
2     0     0     0
3     1     0     1

In [88]:
df.fillna('Missing')

Col1     Col2     Col3
0      1.0      4.0        a
1      2.0  Missing        b
2      3.0      6.0        c
3  Missing      7.0  Missing

In [89]:
df.fillna(df.mean())

C:\Users\DiegoJiménez\AppData\Local\Temp\ipykernel_23532\634187881.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.fillna(df.mean())


Col1      Col2  Col3
0   1.0  4.000000     a
1   2.0  5.666667     b
2   3.0  6.000000     c
3   2.0  7.000000  None

In [92]:
df[['Col1','Col2']].mean()

Col1    2.000000
Col2    5.666667
dtype: float64

In [93]:
df.interpolate()

Col1  Col2  Col3
0   1.0   4.0     a
1   2.0   5.0     b
2   3.0   6.0     c
3   3.0   7.0  None

In [94]:
df.dropna()

Col1  Col2 Col3
0   1.0   4.0    a
2   3.0   6.0    c

## Clase 6 Filtrado por notificaciones

In [95]:
import pandas as pd

In [108]:
df_books = pd.read_csv('./bestsellers-with-categories.csv',sep=',',header=0)
df.head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year        Genre  
0  2016  Non Fiction  
1  2011      Fiction

In [121]:
mayor2016 = df_books['Year'] > 2016

In [122]:
df_books[mayor2016].shape

(150, 7)

In [116]:
df_books.describe

<bound method NDFrame.describe of                                                   Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson

In [119]:
genreFiction = df_books['Genre'] == 'Fiction'
genreFiction #muestra el dataFrame con valores booleanos. True para libros de tipo Fiction

0      False
1       True
2      False
3       True
4      False
       ...  
545     True
546    False
547    False
548    False
549    False
Name: Genre, Length: 550, dtype: bool

In [124]:
df_books[~genreFiction & mayor2016]
#negación con ~

Name  \
2              12 Rules for Life: An Antidote to Chaos   
4    5,000 Awesome Facts (About Everything!) (Natio...   
8        A Higher Loyalty: Truth, Lies, and Leadership   
26                  Astrophysics for People in a Hurry   
32                                            Becoming   
..                                                 ...   
526                                      What Happened   
536  Whose Boat Is This Boat?: Comments That Don't ...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                               Author  User Rating  Reviews  Price  Year  \
2                  Jordan B. Peterson          4.7    18979     15  2018   
4            National Geographic Kids          4.8     7665     12  2019   
8                         James Comey          4.7     5983      3  2018   
26                Neil deGrasse Tyson          4.7     9374      9  2017   
32                     Michelle Obama          4.8    61133     11  2018   
..                                ...          ...      ...    ...   ...   
526            Hillary Rodham Clinton          4.6     5492     18  2017   
536  The Staff of The Late Show with
          4.6     6669     12  2018   
547                       Jen Sincero          4.7    14331      8  2017   
548                       Jen Sincero          4.7    14331      8  2018   
549                       Jen Sincero          4.7    14331      8  2019   

           Genre  
2    Non Fiction  
4    Non Fiction  
8    Non Fiction  
26   Non Fiction  
32   Non Fiction  
..           ...  
526  Non Fiction  
536  Non Fiction  
547  Non Fiction  
548  Non Fiction  
549  Non Fiction  

[85 rows x 7 columns]

## Clase 7 Funciones principales de pandas

In [125]:
import pandas as pd

In [126]:
df_books = pd.read_csv('./bestsellers-with-categories.csv',sep=',',header=0)
df.head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year        Genre  
0  2016  Non Fiction  
1  2011      Fiction

In [ ]:
df_books.head(2) 
#muestra los primeros dos registros del dataFrame 

In [127]:
df_books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Name         550 non-null    object 
 1   Author       550 non-null    object 
 2   User Rating  550 non-null    float64
 3   Reviews      550 non-null    int64  
 4   Price        550 non-null    int64  
 5   Year         550 non-null    int64  
 6   Genre        550 non-null    object 
dtypes: float64(1), int64(3), object(3)
memory usage: 30.2+ KB


In [128]:
df_books.describe()

User Rating       Reviews       Price         Year
count   550.000000    550.000000  550.000000   550.000000
mean      4.618364  11953.281818   13.100000  2014.000000
std       0.226980  11731.132017   10.842262     3.165156
min       3.300000     37.000000    0.000000  2009.000000
25%       4.500000   4058.000000    7.000000  2011.000000
50%       4.700000   8580.000000   11.000000  2014.000000
75%       4.800000  17253.250000   16.000000  2017.000000
max       4.900000  87841.000000  105.000000  2019.000000

In [129]:
df_books.tail(2)

Name       Author  \
548  You Are a Badass: How to Stop Doubting Your Gr...  Jen Sincero   
549  You Are a Badass: How to Stop Doubting Your Gr...  Jen Sincero   

     User Rating  Reviews  Price  Year        Genre  
548          4.7    14331      8  2018  Non Fiction  
549          4.7    14331      8  2019  Non Fiction

In [130]:
df_books.memory_usage(deep=True)

Index            128
Name           59737
Author         39078
User Rating     4400
Reviews         4400
Price           4400
Year            4400
Genre          36440
dtype: int64

In [131]:
df_books['Author'].value_counts()

Jeff Kinney                           12
Gary Chapman                          11
Rick Riordan                          11
Suzanne Collins                       11
American Psychological Association    10
                                      ..
Keith Richards                         1
Chris Cleave                           1
Alice Schertle                         1
Celeste Ng                             1
Adam Gasiewski                         1
Name: Author, Length: 248, dtype: int64

In [133]:
df_books = df_books.append(df_books.iloc[0])

C:\Users\DiegoJiménez\AppData\Local\Temp\ipykernel_23532\3653130519.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_books = df_books.append(df_books.iloc[0])


In [134]:
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   
0                        10-Day Green Smoothie Cleanse   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  

[551 rows x 7 columns]

In [135]:
df_books.drop_duplicates()

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [137]:
df_books.sort_values('Year',ascending=False)

Name                 Author  \
179                       If Animals Kissed Good Night      Ann Whitford Paul   
294  School Zone - Big Preschool Workbook - Ages 4 ...            School Zone   
263    P is for Potty! (Sesame Street) (Lift-the-Flap)        Naomi Kleinberg   
489                   The Wonderful Things You Will Be  Emily Winfield Martin   
267             Player's Handbook (Dungeons & Dragons)       Wizards RPG Team   
..                                                 ...                    ...   
160                  Have a Little Faith: A True Story            Mitch Albom   
512                             True Compass: A Memoir      Edward M. Kennedy   
513               Twilight (The Twilight Saga, Book 1)        Stephenie Meyer   
78   Divine Soul Mind Body Healing and Transmission...           Zhi Gang Sha   
459        The Shack: Where Tragedy Confronts Eternity       William P. Young   

     User Rating  Reviews  Price  Year        Genre  
179          4.8    16643      4  2019      Fiction  
294          4.8    23047      6  2019  Non Fiction  
263          4.7    10820      5  2019  Non Fiction  
489          4.9     8842     10  2019      Fiction  
267          4.8    16990     27  2019      Fiction  
..           ...      ...    ...   ...          ...  
160          4.8     1930      4  2009  Non Fiction  
512          4.5      438     15  2009  Non Fiction  
513          4.7    11676      9  2009      Fiction  
78           4.6       37      6  2009  Non Fiction  
459          4.6    19720      8  2009      Fiction  

[551 rows x 7 columns]

## Clase 8 groupby

In [1]:
import pandas as pd

In [2]:
df_books = pd.read_csv('./bestsellers-with-categories.csv',sep=',',header=0)
df_books.head(3)

Name              Author  User Rating  \
0            10-Day Green Smoothie Cleanse            JJ Smith          4.7   
1                        11/22/63: A Novel        Stephen King          4.6   
2  12 Rules for Life: An Antidote to Chaos  Jordan B. Peterson          4.7   

   Reviews  Price  Year        Genre  
0    17350      8  2016  Non Fiction  
1     2052     22  2011      Fiction  
2    18979     15  2018  Non Fiction

In [7]:
df_books.groupby('Author').count()

Name  User Rating  Reviews  Price  Year  Genre
Author                                                                    
Abraham Verghese               2            2        2      2     2      2
Adam Gasiewski                 1            1        1      1     1      1
Adam Mansbach                  1            1        1      1     1      1
Adir Levy                      1            1        1      1     1      1
Admiral William H. McRaven     1            1        1      1     1      1
...                          ...          ...      ...    ...   ...    ...
Walter Isaacson                3            3        3      3     3      3
William Davis                  2            2        2      2     2      2
William P. Young               2            2        2      2     2      2
Wizards RPG Team               3            3        3      3     3      3
Zhi Gang Sha                   2            2        2      2     2      2

[248 rows x 6 columns]

In [8]:
df_books.groupby('Author').mean()

User Rating       Reviews      Price         Year
Author                                                                       
Abraham Verghese               4.600000   4866.000000  11.000000  2010.500000
Adam Gasiewski                 4.400000   3113.000000   6.000000  2017.000000
Adam Mansbach                  4.800000   9568.000000   9.000000  2011.000000
Adir Levy                      4.800000   8170.000000  13.000000  2019.000000
Admiral William H. McRaven     4.700000  10199.000000  11.000000  2017.000000
...                                 ...           ...        ...          ...
Walter Isaacson                4.566667   6222.666667  20.333333  2013.333333
William Davis                  4.400000   7497.000000   6.000000  2012.500000
William P. Young               4.600000  19720.000000   8.000000  2013.000000
Wizards RPG Team               4.800000  16990.000000  27.000000  2018.000000
Zhi Gang Sha                   4.600000    128.500000  11.500000  2011.000000

[248 rows x 4 columns]

In [9]:
df_books.groupby('Author').max()

Name  \
Author                                                                          
Abraham Verghese                                            Cutting for Stone   
Adam Gasiewski              Milk and Vine: Inspirational Quotes From Class...   
Adam Mansbach                                            Go the F**k to Sleep   
Adir Levy                   What Should Danny Do? (The Power to Choose Ser...   
Admiral William H. McRaven  Make Your Bed: Little Things That Can Change Y...   
...                                                                       ...   
Walter Isaacson                                                    Steve Jobs   
William Davis               Wheat Belly: Lose the Wheat, Lose the Weight, ...   
William P. Young                  The Shack: Where Tragedy Confronts Eternity   
Wizards RPG Team                       Player's Handbook (Dungeons & Dragons)   
Zhi Gang Sha                Soul Healing Miracles: Ancient and New Sacred ...   

                            User Rating  Reviews  Price  Year        Genre  
Author                                                                      
Abraham Verghese                    4.6     4866     11  2011      Fiction  
Adam Gasiewski                      4.4     3113      6  2017  Non Fiction  
Adam Mansbach                       4.8     9568      9  2011      Fiction  
Adir Levy                           4.8     8170     13  2019      Fiction  
Admiral William H. McRaven          4.7    10199     11  2017  Non Fiction  
...                                 ...      ...    ...   ...          ...  
Walter Isaacson                     4.6     7827     21  2017  Non Fiction  
William Davis                       4.4     7497      6  2013  Non Fiction  
William P. Young                    4.6    19720      8  2017      Fiction  
Wizards RPG Team                    4.8    16990     27  2019      Fiction  
Zhi Gang Sha                        4.6      220     17  2013  Non Fiction  

[248 rows x 6 columns]

In [10]:
df_books.groupby('Author').sum()

User Rating  Reviews  Price  Year
Author                                                       
Abraham Verghese                    9.2     9732     22  4021
Adam Gasiewski                      4.4     3113      6  2017
Adam Mansbach                       4.8     9568      9  2011
Adir Levy                           4.8     8170     13  2019
Admiral William H. McRaven          4.7    10199     11  2017
...                                 ...      ...    ...   ...
Walter Isaacson                    13.7    18668     61  6040
William Davis                       8.8    14994     12  4025
William P. Young                    9.2    39440     16  4026
Wizards RPG Team                   14.4    50970     81  6054
Zhi Gang Sha                        9.2      257     23  4022

[248 rows x 4 columns]

In [11]:
df_books.groupby('Author').sum().loc['William Davis']

User Rating        8.8
Reviews        14994.0
Price             12.0
Year            4025.0
Name: William Davis, dtype: float64

In [13]:
df_books.groupby('Author').sum().reset_index()

Author  User Rating  Reviews  Price  Year
0              Abraham Verghese          9.2     9732     22  4021
1                Adam Gasiewski          4.4     3113      6  2017
2                 Adam Mansbach          4.8     9568      9  2011
3                     Adir Levy          4.8     8170     13  2019
4    Admiral William H. McRaven          4.7    10199     11  2017
..                          ...          ...      ...    ...   ...
243             Walter Isaacson         13.7    18668     61  6040
244               William Davis          8.8    14994     12  4025
245            William P. Young          9.2    39440     16  4026
246            Wizards RPG Team         14.4    50970     81  6054
247                Zhi Gang Sha          9.2      257     23  4022

[248 rows x 5 columns]

In [14]:
df_books.groupby('Author').agg(['min','max'])

Name  \
                                                                          min   
Author                                                                          
Abraham Verghese                                            Cutting for Stone   
Adam Gasiewski              Milk and Vine: Inspirational Quotes From Class...   
Adam Mansbach                                            Go the F**k to Sleep   
Adir Levy                   What Should Danny Do? (The Power to Choose Ser...   
Admiral William H. McRaven  Make Your Bed: Little Things That Can Change Y...   
...                                                                       ...   
Walter Isaacson                                             Leonardo da Vinci   
William Davis               Wheat Belly: Lose the Wheat, Lose the Weight, ...   
William P. Young                  The Shack: Where Tragedy Confronts Eternity   
Wizards RPG Team                       Player's Handbook (Dungeons & Dragons)   
Zhi Gang Sha                Divine Soul Mind Body Healing and Transmission...   

                                                                               \
                                                                          max   
Author                                                                          
Abraham Verghese                                            Cutting for Stone   
Adam Gasiewski              Milk and Vine: Inspirational Quotes From Class...   
Adam Mansbach                                            Go the F**k to Sleep   
Adir Levy                   What Should Danny Do? (The Power to Choose Ser...   
Admiral William H. McRaven  Make Your Bed: Little Things That Can Change Y...   
...                                                                       ...   
Walter Isaacson                                                    Steve Jobs   
William Davis               Wheat Belly: Lose the Wheat, Lose the Weight, ...   
William P. Young                  The Shack: Where Tragedy Confronts Eternity   
Wizards RPG Team                       Player's Handbook (Dungeons & Dragons)   
Zhi Gang Sha                Soul Healing Miracles: Ancient and New Sacred ...   

                           User Rating      Reviews        Price      Year  \
                                   min  max     min    max   min max   min   
Author                                                                       
Abraham Verghese                   4.6  4.6    4866   4866    11  11  2010   
Adam Gasiewski                     4.4  4.4    3113   3113     6   6  2017   
Adam Mansbach                      4.8  4.8    9568   9568     9   9  2011   
Adir Levy                          4.8  4.8    8170   8170    13  13  2019   
Admiral William H. McRaven         4.7  4.7   10199  10199    11  11  2017   
...                                ...  ...     ...    ...   ...  ..   ...   
Walter Isaacson                    4.5  4.6    3014   7827    20  21  2011   
William Davis                      4.4  4.4    7497   7497     6   6  2012   
William P. Young                   4.6  4.6   19720  19720     8   8  2009   
Wizards RPG Team                   4.8  4.8   16990  16990    27  27  2017   
Zhi Gang Sha                       4.6  4.6      37    220     6  17  2009   

                                        Genre               
                             max          min          max  
Author                                                      
Abraham Verghese            2011      Fiction      Fiction  
Adam Gasiewski              2017  Non Fiction  Non Fiction  
Adam Mansbach               2011      Fiction      Fiction  
Adir Levy                   2019      Fiction      Fiction  
Admiral William H. McRaven  2017  Non Fiction  Non Fiction  
...                          ...          ...          ...  
Walter Isaacson             2017  Non Fiction  Non Fiction  
William Davis               2013  Non Fiction  Non Fiction  
William P. Young            2017      F

In [15]:
df_books.groupby('Author').agg({'Reviews':['min','max'],'User Rating':'sum'})

Reviews        User Rating
                               min    max         sum
Author                                               
Abraham Verghese              4866   4866         9.2
Adam Gasiewski                3113   3113         4.4
Adam Mansbach                 9568   9568         4.8
Adir Levy                     8170   8170         4.8
Admiral William H. McRaven   10199  10199         4.7
...                            ...    ...         ...
Walter Isaacson               3014   7827        13.7
William Davis                 7497   7497         8.8
William P. Young             19720  19720         9.2
Wizards RPG Team             16990  16990        14.4
Zhi Gang Sha                    37    220         9.2

[248 rows x 3 columns]

In [16]:
df_books.groupby(['Author','Year']).count()

Name  User Rating  Reviews  Price  Genre
Author           Year                                          
Abraham Verghese 2010     1            1        1      1      1
                 2011     1            1        1      1      1
Adam Gasiewski   2017     1            1        1      1      1
Adam Mansbach    2011     1            1        1      1      1
Adir Levy        2019     1            1        1      1      1
...                     ...          ...      ...    ...    ...
Wizards RPG Team 2017     1            1        1      1      1
                 2018     1            1        1      1      1
                 2019     1            1        1      1      1
Zhi Gang Sha     2009     1            1        1      1      1
                 2013     1            1        1      1      1

[493 rows x 5 columns]

## Clase 9/10 combinación de dataframes (Concat y Merge)

- Merge
- Join
- Concat

Para fusionar dataframes

In [18]:
import pandas as pd
import numpy as np

In [19]:
df1 = pd.DataFrame({
    'A':['A0', 'A1', 'A2','A3'],
    'B':['B0', 'B1', 'B2','B3'],
	'C':['C0', 'C1', 'C2','C3'],
	'D':['D0', 'D1', 'D2','D3']
    })


df2 = pd.DataFrame({
    'A':['A4', 'A5', 'A6','A7'],
	'B':['B4', 'B5', 'B6','B7'],
	'C':['C4', 'C5', 'C6','C7'],
	'D':['D4', 'D5', 'D6','D7']
    })

In [22]:
df1.head()

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [21]:
df2.head()

A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [26]:
pd.concat([df1,df2],ignore_index=True)

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [27]:
pd.concat([df1,df2],axis=1)

A   B   C   D   A   B   C   D
0  A0  B0  C0  D0  A4  B4  C4  D4
1  A1  B1  C1  D1  A5  B5  C5  D5
2  A2  B2  C2  D2  A6  B6  C6  D6
3  A3  B3  C3  D3  A7  B7  C7  D7

In [28]:
izq = pd.DataFrame({'key' : ['k0', 'k1', 'k2','k3'],
 'A' : ['A0', 'A1', 'A2','A3'],
'B': ['B0', 'B1', 'B2','B3']})

der = pd.DataFrame({'key' : ['k0', 'k1', 'k2','k3'],
 'C' : ['C0', 'C1', 'C2','C3'],
'D': ['D0', 'D1', 'D2','D3']})

In [29]:
izq

key   A   B
0  k0  A0  B0
1  k1  A1  B1
2  k2  A2  B2
3  k3  A3  B3

In [31]:
der

key   C   D
0  k0  C0  D0
1  k1  C1  D1
2  k2  C2  D2
3  k3  C3  D3

In [32]:
izq.merge(der,on='key')

key   A   B   C   D
0  k0  A0  B0  C0  D0
1  k1  A1  B1  C1  D1
2  k2  A2  B2  C2  D2
3  k3  A3  B3  C3  D3

In [33]:
der = pd.DataFrame({'key_2' : ['k0', 'k1', 'k2','k3'],
 'C' : ['C0', 'C1', 'C2','C3'],
'D': ['D0', 'D1', 'D2','D3']})

In [34]:
izq.merge(der,left_on='key',right_on='key_2')

key   A   B key_2   C   D
0  k0  A0  B0    k0  C0  D0
1  k1  A1  B1    k1  C1  D1
2  k2  A2  B2    k2  C2  D2
3  k3  A3  B3    k3  C3  D3

In [37]:
izq = pd.DataFrame({'key' : ['k0', 'k1', 'k2','k3'],
 'A' : ['A0', 'A1', 'A2','A3'],
'B': ['B0', 'B1', 'B2','B3']})

der = pd.DataFrame({'key_2' : ['k0', 'k1', 'k2',np.nan],
 'C' : ['C0', 'C1', 'C2','C3'],
'D': ['D0', 'D1', 'D2','D3']})


In [40]:
izq.merge(der,left_on='key',right_on='key_2',how='outer')

key    A    B key_2    C    D
0   k0   A0   B0    k0   C0   D0
1   k1   A1   B1    k1   C1   D1
2   k2   A2   B2    k2   C2   D2
3   k3   A3   B3   NaN  NaN  NaN
4  NaN  NaN  NaN   NaN   C3   D3

## Clase 11 join

La diferencia con Merge es que Join va directo a los indices y Merge a las columnas

In [42]:
import pandas as pd

In [41]:
izq = pd.DataFrame({'A': ['A0','A1','A2'],
  'B':['B0','B1','B2']},
  index=['k0','k1','k2'])

der =pd.DataFrame({'C': ['C0','C1','C2'],
  'D':['D0','D1','D2']},
  index=['k0','k2','k3']) 

In [44]:
izq.join(der,how='outer')

A    B    C    D
k0   A0   B0   C0   D0
k1   A1   B1  NaN  NaN
k2   A2   B2   C1   D1
k3  NaN  NaN   C2   D2

## Clase 12  pivot_table y melt

In [47]:
df_books = pd.read_csv('./bestsellers-with-categories.csv',sep=',',header=0)


In [48]:
df_books.head()


Name  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  Price  Year        Genre  
0                  JJ Smith          4.7    17350      8  2016  Non Fiction  
1              Stephen King          4.6     2052     22  2011      Fiction  
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3             George Orwell          4.7    21424      6  2017      Fiction  
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction

In [49]:
df_books.pivot_table(index='Author',columns='Genre',values='User Rating')


Genre                       Fiction  Non Fiction
Author                                          
Abraham Verghese                4.6          NaN
Adam Gasiewski                  NaN     4.400000
Adam Mansbach                   4.8          NaN
Adir Levy                       4.8          NaN
Admiral William H. McRaven      NaN     4.700000
...                             ...          ...
Walter Isaacson                 NaN     4.566667
William Davis                   NaN     4.400000
William P. Young                4.6          NaN
Wizards RPG Team                4.8          NaN
Zhi Gang Sha                    NaN     4.600000

[248 rows x 2 columns]

In [50]:
df_books.pivot_table(index='Genre',columns='Year', values='User Rating',aggfunc='sum')


Year          2009   2010   2011   2012   2013   2014   2015   2016   2017  \
Genre                                                                        
Fiction      110.2   92.3   97.0   94.4  109.1  134.3   79.1   89.6  113.7   
Non Fiction  119.0  135.6  130.9  132.2  118.6   96.8  153.3  144.3  119.3   

Year          2018   2019  
Genre                      
Fiction       99.5   96.4  
Non Fiction  133.9  140.6

In [51]:
df_books[['Name','Genre']].head(5)

Name        Genre
0                      10-Day Green Smoothie Cleanse  Non Fiction
1                                  11/22/63: A Novel      Fiction
2            12 Rules for Life: An Antidote to Chaos  Non Fiction
3                             1984 (Signet Classics)      Fiction
4  5,000 Awesome Facts (About Everything!) (Natio...  Non Fiction

In [52]:
df_books[['Name','Genre']].head(5).melt()


variable                                              value
0     Name                      10-Day Green Smoothie Cleanse
1     Name                                  11/22/63: A Novel
2     Name            12 Rules for Life: An Antidote to Chaos
3     Name                             1984 (Signet Classics)
4     Name  5,000 Awesome Facts (About Everything!) (Natio...
5    Genre                                        Non Fiction
6    Genre                                            Fiction
7    Genre                                        Non Fiction
8    Genre                                            Fiction
9    Genre                                        Non Fiction

In [53]:
df_books.melt(id_vars='Year',value_vars='Genre')


Year variable        value
0    2016    Genre  Non Fiction
1    2011    Genre      Fiction
2    2018    Genre  Non Fiction
3    2017    Genre      Fiction
4    2019    Genre  Non Fiction
..    ...      ...          ...
545  2019    Genre      Fiction
546  2016    Genre  Non Fiction
547  2017    Genre  Non Fiction
548  2018    Genre  Non Fiction
549  2019    Genre  Non Fiction

[550 rows x 3 columns]

## Clase 13 Apply

In [55]:
import pandas as pd

df_books = pd.read_csv('./bestsellers-with-categories.csv',sep=',',header=0)
df_books.head()

Name  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  Price  Year        Genre  
0                  JJ Smith          4.7    17350      8  2016  Non Fiction  
1              Stephen King          4.6     2052     22  2011      Fiction  
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3             George Orwell          4.7    21424      6  2017      Fiction  
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction

In [56]:
def two_times(value):
    return value * 2

In [60]:
df_books['Rating_2'] = df_books['User Rating'].apply(two_times)

In [72]:
df_books.head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year        Genre  Rating_2  Rating_3  Rating_Fiction  
0  2016  Non Fiction       9.4      14.1             4.7  
1  2011      Fiction       9.2      13.8             9.2

In [68]:
df_books['Rating_3'] = df_books['User Rating'].apply(lambda x : x * 3)

In [71]:
df_books['Rating_Fiction'] = df_books.apply(lambda x: x['User Rating'] * 2 if x['Genre'] == 'Fiction' else x['User Rating'], axis = 1)

In [77]:
np.linspace(0,10,100)
np.expand_dims()

1

In [79]:
arr = np.array([13, 6, 3, 5, 10])
arr[arr>7]

array([13, 10])

In [84]:
np.array([[7,8],
[2,1],
[2,4]]).shape

(3, 2)