# Numpy

## Clase 4 Dimensiones

- 0 Escalar
- 1 Vector
- 2 matriz
- [3,N] tensor

In [297]:
import numpy as np

In [298]:
scalar = np.array(42)
print(scalar)
print("Dimensión: ",scalar.ndim)

42
Dimensión:  0


In [299]:
vector = np.array([1,2,3])
print(vector)
print("Dimensión: ",vector.ndim)

[1 2 3]
Dimensión:  1


In [300]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
print("Dimensión: ",matriz.ndim)

[[1 2 3]
 [4 5 6]]
Dimensión:  2


In [301]:
tensor = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(tensor)
print("Dimensión: ",tensor.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Dimensión:  3


### Agregar o eliminar dimensiones

In [302]:
vector = np.array([1,2,3], ndmin=10)
print(vector)
print("Dimensión: ",vector.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]]
Dimensión:  10


In [303]:
expand = np.expand_dims(np.array([1,2,3]),axis=0)
print(expand)
print("Dimensión: ",expand.ndim)

[[1 2 3]]
Dimensión:  2


In [345]:
expand = np.expand_dims(np.array([1,2,3]),axis=1)
print(expand)
print("Dimensión: ",expand.ndim)

[[1]
 [2]
 [3]]
Dimensión:  2


In [344]:
print(vector,"Dimensión: ",vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2,"Dimensión: ",vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] Dimensión:  10
[1 2 3] Dimensión:  1


## Clase 5 Creación de arrays en numpy

In [305]:
import numpy as np

In [306]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [307]:
np.arange(-10,11,2)

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8,  10])

In [308]:
np.zeros(3)

array([0., 0., 0.])

In [309]:
np.ones((10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [310]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [311]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [312]:
np.random.rand()

0.5790626396738328

In [313]:
np.random.rand(4,4)

array([[0.28826335, 0.38325896, 0.65344757, 0.16005495],
       [0.62823407, 0.51415049, 0.51944943, 0.58874548],
       [0.56408662, 0.55452156, 0.24764998, 0.56101454],
       [0.79785667, 0.11079478, 0.17530035, 0.99469361]])

In [314]:
np.random.randint(1,100)

47

In [315]:
np.random.randint(0,100,(5,5))

array([[45, 77, 28, 38, 87],
       [ 5, 77, 23,  0, 94],
       [23, 52, 33, 35, 56],
       [49,  8, 52, 87, 44],
       [19, 69, 24, 47, 28]])

## Clase 6 Shape and Reshape

- Sirve para ...

In [316]:
import numpy as np

In [317]:
arr = np.random.randint(1,100,(3,2))
arr

array([[55, 10],
       [64, 60],
       [96, 46]])

In [318]:
# Muestra las cantidades por als dimensiones 3x2
arr.shape

(3, 2)

In [319]:
# Reshape cambia la forma en la que se establece el array de 3x2 a 1x6
arr.reshape(1,6)

array([[55, 10, 64, 60, 96, 46]])

In [320]:
arr.reshape(2,3)

array([[55, 10, 64],
       [60, 96, 46]])

In [321]:
arr.reshape(3,2)

array([[55, 10],
       [64, 60],
       [96, 46]])

In [322]:
# Como en el lenguaje C
np.reshape(arr,(2,3),'C')

array([[55, 10, 64],
       [60, 96, 46]])

In [323]:
# Como en el lenguaje Fortran
np.reshape(arr,(2,3),'F')

array([[55, 96, 60],
       [64, 10, 46]])

In [324]:
# selecciona el array en forma de leguaje C o Fortran
np.reshape(arr,(2,3),'A')

array([[55, 10, 64],
       [60, 96, 46]])

## Clase 7 Funciones principales de Numpy

In [325]:
import numpy as np

In [326]:
arr = np.random.randint(1,20,10)
arr

array([19, 19, 15,  6, 11,  6, 16, 13, 12, 14])

In [327]:
matriz = arr.reshape(2,5)
matriz

array([[19, 19, 15,  6, 11],
       [ 6, 16, 13, 12, 14]])

In [328]:
#Función MAX (trae el número mayor)
arr.max()

19

In [329]:
#por renglon
print(matriz.max(1))
# por columna
print(matriz.max(0))

[19 16]
[19 19 15 12 14]


In [330]:
# indice de valor máximo (muestra el de menor indice)
arr.argmax()

0

In [331]:
matriz.argmax(0)

array([0, 0, 0, 1, 1], dtype=int64)

In [332]:
# Similar a min para el minimo
matriz.min(0)

array([ 6, 16, 13,  6, 11])

In [333]:
matriz.argmin(0)

array([1, 1, 1, 0, 0], dtype=int64)

In [334]:
# función peak to peak (del menor al mayor)
print(arr)
arr.ptp()

[19 19 15  6 11  6 16 13 12 14]


13

In [335]:
arr.sort()
arr

array([ 6,  6, 11, 12, 13, 14, 15, 16, 19, 19])

In [336]:
np.percentile(arr,50)

13.5

### funciones estadisticas

In [337]:
np.median(arr)

13.5

In [338]:
np.std(arr)

4.346262762420146

In [339]:
np.var(arr)

18.89

In [340]:
np.std(arr) ** 2

18.889999999999997

In [341]:
np.mean(arr)

13.1

In [342]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [343]:
np.concatenate((a,b),axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
print(a.ndim)
print(b.ndim)

2
1


In [ ]:
b=np.expand_dims(b,axis=0)
b

array([[5, 6]])

In [ ]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.concatenate((a,b),axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [ ]:
#Transpuesta
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
print(b)
print(b.T)

[[5 6]]
[[5]
 [6]]


## Clase 8 Función Copy

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
trozo_arr = arr[0:6]
trozo_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
trozo_arr[:] = 0
trozo_arr

array([0, 0, 0, 0, 0, 0])

In [ ]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [ ]:
arr_copy = arr.copy()
arr_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [ ]:
arr_copy[:] = 1
print(arr_copy)
print(arr)

[1 1 1 1 1 1 1 1 1 1 1]
[ 0  0  0  0  0  0  6  7  8  9 10]


## Clase 9 Condiciones

In [ ]:
import numpy as np

In [ ]:
arr = np.linspace(1,10,10,dtype='int8')

In [ ]:
indices_condicion = arr > 5
indices_condicion

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [ ]:
arr[indices_condicion]
#or
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [ ]:
arr[(arr > 5) & (arr<9)]

array([6, 7, 8])

In [ ]:
arr[arr > 5 ] = 99
arr

array([ 1,  2,  4,  4,  5, 99, 99, 99, 99, 99])

## Clase 10 Operaciones

In [ ]:
import numpy as np

In [ ]:
lista = [1,2]
lista

[1, 2]

In [ ]:
lista * 2

[1, 2, 1, 2]

In [ ]:
arr = np.arange(0,10)
arr2 = arr.copy()

Operaciones

In [ ]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
1 / arr

C:\Users\Diego\AppData\Local\Temp\ipykernel_3584\1528351372.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [ ]:
np.matmul(matriz,matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [ ]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])

# Pandas

## Clase 1 Series y Dataframse en Pandas

Pandas maneja 2 objetos principales 

Pandas Series
y
Pandas Dataframe